version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkinsnet

volumes:
  jenkins_home:

networks:
  jenkinsnet: