version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: 
      # MYSQL_DATABASE: your_database_name
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/mysql
    container_name: mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
